extends:
  - airbnb-base
  - plugin:@typescript-eslint/recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:import/typescript
plugins:
  - "@typescript-eslint"
  - jest
  - import
parser: "@typescript-eslint/parser"
parserOptions:
  sourceType: module
env:
  node: true
  jest/globals: true,
settings:
  node:
    tryExtensions:
      - .ts
      - .js
      - .json
  import/extensions:
    - .ts
    - .js
  import/resolver:
    node:
      paths:
        - bin
        - lib
        - test
      extensions:
        - .js
        - .ts
ignorePatterns:
  - bin/**/*.js
  - lib/**/*.js
  - test/**/*.js
  - bin/**/*.d.ts
  - lib/**/*.d.ts
  - test/**/*.d.ts
rules:
  import/extensions:
    - error
    - ignorePackages
    - js: never
      ts: never
  import/prefer-default-export: off
  no-useless-constructor: 0
  no-new: 0
  "@typescript-eslint/no-unused-vars": error
  lines-between-class-members: [error, always, { exceptAfterSingleLine: true }]
